### ISSUE TITLE
lb-ng Hanging on Windows

### ISSUE THREAD

**Issue by adriangordon1231** [strongloop/loopback-sdk-angular-cli#65]
Everytime I run the lb-ng command it hangs on "Saving the generated services source". Inevitably, I will get tired of waiting and stop the process (manually). However, when actually check the file that was generated, it contains all of the correct models and endpoints I defined in my API.

I am not 100% certain that this is a reproducible error, however I would love to know if anyone else is experiencing this same issue.

Node - 6.9.1
Operating System - Windows 10

**Comment by bajtos** [comment]
`lb-ng` usually hangs when the application does not exit after it was `require()`. `lb-ng` is explicitly calling `process.exit` to address that situation.

I think the problem  was introduced by #45  and then fixed by #62.

I am going to close this issue as fixed, please reopen it if the problem persists.
