### ISSUE TITLE
not able to generate all the models

### ISSUE THREAD

**Issue by jjhesk** [strongloop/loopback-sdk-angular-cli#68]
The folder contains all different type of models, including database and the local storage. lb-ng doesnt generator appropriate models in the `lb-services-s.js` from the commend. Are there any fixes from such issues? The issue is at version of the loopback system which runs on `v3.0.0-beta`. Im currently looking for a way to make `lb-ng` generator to works with the latest loopback. @bajtos @davidcheung @pthieu  

So i just tried to reinstall `lb-ng` again with the latest version. It got that working but no responses to me. When does the latest 3.0.0 cli release? our roadmap is stuck on this thing now..

**Comment by bajtos** [comment]
@jjhesk How can we reproduce the issue on our machines? Could you please create a small app reproducing the issue per our [bug reporting instructions](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report)?

**Comment by jjhesk** [comment]
@bajtos the issue is produced in here https://github.com/ONode/loopback-sandbox

**Comment by jjhesk** [comment]
instruction to setup:

## getting started
Clone the repository from this branch
1. Install and run backend in the folder
```
npm install
node .
```

2. Open new tab and install and run frontend
```
cd client
npm install && bower install
gulp
```

3. Rebuild the backend (e.g. after model changes) 
```
npm install -g yo bower generator-aaal
rm -r client/app/scripts/aaal
cd client && yo aaal
```


task 3 will actually calling the `lb-ng` when the have sdk-angular-cli installed on the global level.

**Comment by bajtos** [comment]
Thank you for the instructions. I was able to reproduce the problem using the following simpler steps (all executed in the root of your sandbox project):

1) `npm install`
2) `lb-ng server/server.js lb-services.js`
3) The generated file does not contain any models.

More observations:
 - Interestingly enough, when I start the server via `node .` and open Explorer, there are several models shown in the UI.

 - When I temporarily modify the CLI script to wait 500ms before calling `runGenerator`, the issue goes away (see https://github.com/strongloop/loopback-sdk-angular-cli/blob/d3463b0272133747c14d4b9c99c6ee1c8d083a20/bin/lb-ng.js#L38).

 - When I downgrade loopback-boot from `3.0.0-alpha.1` to `latest` (`2.23.0`) in the sandbox project, the problem goes away too.

I suspect this is a bug in loopback-boot@3.x, where it does not correctly set `app.booting` property.

@davidcheung I am leaving this issue for you to investigate more, since you are most familiar with the new loopback-boot version and also with `lb-ng` tool.

cc @raymondfeng as the original author of the new loopback-boot 3.x code.

**Comment by fmtoffolo** [comment]
I was able to get it to work by adding a timeout. But this problem is also affecting custom scripts that want to use the server models. Is there a permanent fix?

**Comment by ihr-it-projekt** [comment]
any update or solutions?

**Comment by Silverkron** [comment]
Same problem. Any solution? Do you want help with a pull-request?

**Comment by bajtos** [comment]
_Cross-posting from https://github.com/strongloop/loopback-sdk-angular-cli/pull/81#discussion_r264647085_

I think I have encountered this issue while working on loopback-next too. Apparently, `loopback-boot@3` is setting the `app.booting` flag a later turn of the event loop.

The flag can have one of the following values:
- `undefined`: boot has not started yet or is in (early) progress
- `true`: boot is in progress
- `false`: boot was finished

@raymondfeng WDYT, can we fix this problem in `loopback-boot`, instead of having to work around it in `lb-ng` and later in LB4 compatibility booters?

**Comment by bajtos** [comment]
I think it will be best to fix this problem in loopback-boot, see https://github.com/strongloop/loopback-boot/pull/286
